[package]
name = "iota-client"
version = "1.0.1"
authors = ["Thoralf Müller <thoralf.mueller@iota.org", "Antony Dikov <antoni.dikov@iota.org>", "Bing-Yang Lin <bingyang.lin@iota.org>", "Lucas Nogueira <lucas.nogueira@iota.org>", "Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use IOTA APIs"
readme = "README.md"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://www.iota.org"
documentation = "https://docs.rs/iota-client"
license = "Apache-2.0"

[lib]
name = "iota_client"

[dependencies]
# TODO: Use crates.io versions when bee-rest-api got updated.
# bee-rest-api = "0.1"
# bee-message = "0.1"
# bee-pow = "0.1"
# bee-common = "0.4"

bee-rest-api = { git = "https://github.com/iotaledger/bee", rev = "8799deaa44e99eaee01e9444a403ba4f2a75727c" }
bee-message = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-pow = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-common = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
iota-crypto = { version = "0.7.0", features = ["std", "blake2b", "ed25519", "random", "slip10", "bip39", "bip39-en"]}
url = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
tokio = { version = "1.5", features = ["macros", "sync", "rt-multi-thread", "rt", "time"], optional = true }
thiserror = "1.0"
num_cpus = "1.13"
log= "0.4"
regex = "1.4"
zeroize = { version = "1.2", features = ["zeroize_derive"] }

# sync
ureq = { version = "2.1", features = ["json"], optional = true }
# async
reqwest = { version = "0.11", features = ["json", "rustls-tls", "blocking"], default-features = false, optional = true }
futures = { version = "0.3", optional = true }

# MQTT
rumqttc = { version = "0.5", features = ["websocket"], optional = true}
# also used for storage
once_cell = { version = "1.7", optional = true }

# storage
async-trait = "0.1"
rusqlite = { version = "0.24", features = ["bundled"], optional = true }

# wasm
# patched version to work in browser and node.js
wasm-timer = { git = "https://github.com/PhilippGackstatter/wasm-timer", rev = "8c619e895ce0b74e3aab86f5758d89b3e6d2567a", optional = true }
# single thread pow for wasm
bee-crypto = { version = "0.2.1-alph", optional = true }
bee-ternary = { version = "0.4.2-alpha", optional = true }
bytes = { version = "1.0", optional = true }

[features]
default = ["async"]
sync = ["ureq", "tokio", "futures"]
async = ["reqwest", "futures", "tokio"]
mqtt = ["rumqttc", "once_cell", "futures"]
storage = ["rusqlite", "once_cell"]
wasm = ["reqwest", "futures", "wasm-timer", "bee-crypto", "bee-ternary", "bytes"]
